### ISSUE TITLE
Eintrag Map

### ISSUE THREAD

**Issue by michaelwandel** [FriendsOfREDAXO/community#100]
Add or update your maps entry? → Please fill out the required fields below.
Your issue relates to another topic? → Please clear this text field and enter your text.

* name: Michael Wandel | heykoeln by THAVIS
* latitude:50.8974570
* longitude:7.0678190
* bio:Seit über 10 Jahren Webseitenentwicklung und -Design mit Redaxo, Addon-Entwicklung, mehr als 100 Webseiten mit Redaxo
* image:http://www.heykoeln.de/files/img/heykoeln-logo.jpg
* links:http://heykoeln.de, http://thavis.com

See `_directory/.data.example.yml` for detailed instructions!

**Comment by schuer** [comment]
Hey Michael, schön dich zu sehen! Aber können wir dein GitHub-Bild statt des Firmenlogos nehmen. Denn die Karte soll für Personen sein, nicht für Unternehmen.

**Comment by michaelwandel** [comment]
Aah klar, kein Problem sorry, ist zwar ein altes Bild aber passt schon ☺


Mit freundlichen Grüßen

Michael Wandel
Projektleiter / Geschäftsführer

—
THAVIS GmbH & Co. KG
Agentur für 3D-Visualisierung & -Animation
Theodor-Heuss-Straße 43-45, 51149 Köln

Tel.: 02203 98871-22
Fax: 02203 98871-71
wandel@thavis.com
www.thavis.com

THAVIS GmbH & Co. KG — Sitz der Gesellschaft: 51149 Köln ∙ Amtsgericht Köln HRA 25746 ∙ UStID DE258512124
Persönlich haftender Gesellschafter: THAVIS Media GmbH ∙ Sitz der Gesellschaft: 51149 Köln ∙ Amtsgericht Köln HRB 62399
Geschäftsführer: Stefan Bleicker, Martin Hömmerich, Peter Krone, Michael Wandel. Es gelten unsere allgemeinen Geschäftsbedingungen.

Von: Dirk Schürjohann <notifications@github.com>
Antworten an: FriendsOfREDAXO/community <reply@reply.github.com>
Datum: Mittwoch, 15. November 2017 um 16:40
An: FriendsOfREDAXO/community <community@noreply.github.com>
Cc: Michael Wandel <wandel@thavis.com>, Author <author@noreply.github.com>
Betreff: Re: [FriendsOfREDAXO/community] Eintrag Map (#100)


Hey Michael, schön dich zu sehen! Aber können wir dein GitHub-Bild statt des Firmenlogos nehmen. Denn die Karte soll für Personen sein, nicht für Unternehmen.
