### ISSUE TITLE
Eintrag Map

### ISSUE THREAD

**Issue by meugel** [FriendsOfREDAXO/community#104]
Add or update your maps entry? → Please fill out the required fields below.
Your issue relates to another topic? → Please clear this text field and enter your text.

- name: Michael Kaser
- latitude: 48.20468
- longitude: 16.34331
- bio: "I'm a (web-)designer for more than 20 years and REDAXO user since 2009, mostly between Vienna and South Tyrol. Always online, sometimes lost."
- image: 
![michaelkaser](https://user-images.githubusercontent.com/6794962/32848541-0dcc1742-ca2d-11e7-8481-e3223a8f0eb2.jpg)
- links: http://michaelkaser.com
See `_directory/.data.example.yml` for detailed instructions!

**Comment by schuer** [comment]
🎉

**Comment by meugel** [comment]
danke!

lg michael
