### ISSUE TITLE
Button und Marker für den REDAXO-Tag

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/community#124]
Sobald der Termin und die Location fix sind :)

**Comment by staabm** [comment]
vllt auch die locations der vergangenen redaxo tage auflisten, mit link zur redaxo.org news?

**Comment by schuer** [comment]
Hatte ich auch schonmal drüber nachgedacht, dann aber verworfen. Könnte zu voll werden und die Karte zu wischiwaschi machen, oder?
Aktuell würde ich denken, dass man immer nur max 1 Specialmarker einblendet.

**Comment by staabm** [comment]
wenn du eine "kategorie events" hast (vllt in anderer farbe), könntest du so auch zeigen in welchem raum sich redaxo events abspielen, nicht nur wo die personen sind.

**Comment by schuer** [comment]
Ja, stimmt, das wäre eine Option.
(Ich persönlich bin nachwievor etwas kritisch gegenüber dem Feature, weil es die Karte komplexer machen würde, aber wie immer entscheidet bei FOR ja die Mehrheit. Insofern: Schauen wir einfach mal, wo es hinführt.)

**Comment by olien** [comment]
Ich fände Marker für Events klasse. Der Marker für den kommenden REDAXO Tag könnte dann größer sein :-). Vielleicht kann es eine Funktion geben um die Marker ein oder auszublenden und beim ersten Aufruf sind die Marker (bis auf den kommenden REDAXO Tag) ausgeblendet...

**Comment by staabm** [comment]
jepp wenn die marker je nach typ in einem unterschiedlichen layer wären könnte man diese ein/ausblenden

**Comment by alexplusde** [comment]
vergangene Termine
04.05.2019 Landshut
14.04.2018 Berlin
04.09.2017 Fulda
14.01.2017 Wackershofen
04.06.2016 Essen
31.10.2015 Frankfurt
25.05.2013 Essen
12.11.2011 Frankfurt
21.11.2009 Wiesbaden
xx.xx.xxxx Wiesbaden

**Comment by tbaddade** [comment]
> xx.xx.xxxx Wiesbaden

02.06.2008
_via Rüdiger_

**Comment by schuer** [comment]
Danke für die Diskussion. Ich schließe hier mal, okay. Bei Bedarf gerne wieder öffnen.
