### ISSUE TITLE
Eintrag Community-Map

### ISSUE THREAD

**Issue by hachmann23** [FriendsOfREDAXO/community#136]
Add or update your maps entry? → Please fill out the required fields below.
Your issue relates to another topic? → Please clear this text field and enter your text.

* nick/name: Silke Hachmann
* latitude: 51.61869595
* longitude: 7.91900617199066
* personal bio: "Hey, ich bin Silke, arbeite und lebe in Welver. Seit 2007 und Version 3.2 bin ich REDAXO treu (und werde es auch bleiben)."

* personal image: logo_hachmann.png
![logo_hachmann](https://user-images.githubusercontent.com/34157734/33486093-1a372c3c-d6a9-11e7-96be-b2c7de4347b2.png)

* links: https://www.hachmann-design.de

**Comment by schuer** [comment]
Hey Silke, danke! Eine Sache: Hättest du Lust, ein anderes Bild zu verwenden? Kein Logo, sondern eins von dir als Person? Wir wollen die Map ja vor allem auf Menschen ausrichten.
Es haben nun allerdings auch schon ein paar Leute auf der Karte ein Bild verwendet, das eher Logo als Person ist, deshalb: Wenn du unbedingt das grüne Icon verwenden möchtest, dann wird dich niemand aufhalten. Aber cooler wäre ein echtes Profilbild. :)

**Comment by schuer** [comment]
(Mit Silke im Slack besprochen, dass sie vermutlich noch ein anderes Bild nachreicht. So lange nehmen wir das Logo.)

**Comment by schuer** [comment]
https://friendsofredaxo.github.io/community/#silkehachmann
