### ISSUE TITLE
Eintrag Map

### ISSUE THREAD

**Issue by metaphon** [FriendsOfREDAXO/community#145]
Add or update your maps entry? → Please fill out the required fields below.
Your issue relates to another topic? → Please clear this text field and enter your text.

    name: Jürgen Eggers | Innovative Internetlösungen
    latitude:52.826372
    longitude:10.083484
    bio: Websites und Webanwendungen - Entwicklung von Addons und Modulen für Redaxo seit 2010.
    image:https://www.innovative-internetloesungen.de/img/17-06-26_juergen-eggers.jpg
    links:https://www.innovative-internetloesungen.de/

See _directory/.data.example.yml for detailed instructions!

**Comment by schuer** [comment]
🎉 
#147

**Comment by metaphon** [comment]
Danke!
