### ISSUE TITLE
map eintrag

### ISSUE THREAD

**Issue by contrastm** [FriendsOfREDAXO/community#158]
Add or update your maps entry? → Please fill out the required fields below.
Your issue relates to another topic? → Please clear this text field and enter your text.

* nick/name: Jens Lindmayer
* latitude: 54.517014
* longitude: 13.636230
* personal bio: Seit vielen Jahren. Viele Websites. Und fast alle mit Redaxo.
* personal image:
* links: http://www.contrast-m.de

See `_directory/.data.example.yml` for detailed instructions!

**Comment by schuer** [comment]
Hey @contrastm, magst du vielleicht deinen richtigen Namen angeben? Für mein Gefühl ist das sonst zu sehr ein Firmeneintrag, wir möchten die Karte aber auf Personen ausrichten.

**Comment by schuer** [comment]
Hey, nochmal ein Reminder. Wäre schön, dich mit Namen auf der Map zu sehen! :)

**Comment by schuer** [comment]
Oh, ich sehe gerade, dass das Issue ja vor 28 Tagen editiert worden ist. Super, so passt es, ich nehme es gleich auf! 👍

**Comment by schuer** [comment]
🎉  https://friendsofredaxo.github.io/community/#contrast-m

**Comment by schuer** [comment]
Endlich mal REDAXO auf einer Insel. Willkommen!
