### ISSUE TITLE
Zusätzliche Listenansicht der Einträge

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/community#161]
Wie wäre es mit einer zusätzlichen Listenansicht der Einträge?
Natürlich nur optional einblendbar...

**Comment by staabm** [comment]
am besten auch durchsuchbar

**Comment by schuer** [comment]
Könnten wir mit der Suche (#85) verknüpfen. Die soll ein Auto-Suggest bekommen, und das könnte man initial oder per Aktion als komplette Liste ausgeben lassen.
