### ISSUE TITLE
validate data.yml file

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/community#17]
would be great if we could validate the yml file somehow, so syntactical incorrect or "wrongly-keyed" data files can be detected pre-merge.

**Comment by schuer** [comment]
Yeah, would be meaningful. Help appreciated!

**Comment by schuer** [comment]
Remember to parse the [Front Matter](https://jekyllrb.com/docs/frontmatter/) blocks defined by triple-dashed lines at the top and bottom of the file!

```
---

   {yml here}

---
```
