### ISSUE TITLE
Hide commented out yml entries for lat/long

### ISSUE THREAD

**Issue by kermie** [FriendsOfREDAXO/community#171]
Yaml-based files on GitHub are a very welcome database replacement, especially when it comes to community driven alterations or deletions.

Additionally, other parameters might be entered that do not appear in the maps but might be used in other applications that use data.yml files as a single source database - just one place for it all. 

As a freelancer, for example, I'd like to enter my database prefix used in my projects: This information will (correctly) not appear in the map and might be used elsewhere for being displayed on any website. In case my business is gone, the DB prefix shall still appear on the website (so the user might turn to me, requesting support. On the other hand, I don't want to promote my business connections via the community map any more to get no more business requests.

Commenting out longitude and latitude of my personal entry, ports me directly south of Ghana | west of Gabon (is it 0|0?).

Would it be possible to hide an entry with 0|0?

**Comment by schuer** [comment]
Thanks for your feedback! Shouldn’t be a problem to not show entries missing the lng/lat value. I probably just missed to implement the check. Will take care of it, thanks!

**Comment by schuer** [comment]
Hey @kermie, issue has been fixed. I had to restructure the HTML and move the data block up into the <head> section to allow for values being used afterwards inside the body. So in case you modified your `index.html`, have a look at the new structure.
