### ISSUE TITLE
Array for more than one lat/long possible?

### ISSUE THREAD

**Issue by kermie** [FriendsOfREDAXO/community#172]
As we have some community members with more than one branch office: would it be possible to have more than one lat/long assignment per file » AKA, would it be possible to have an array for longitude and latitude in a single yaml file?

**Comment by schuer** [comment]
From the dev point of view using an array wouldn’t be a big deal. However, for REDAXO we decided to keep it simple and use **one marker per person** only, and if anyone requires more than one they should add multiple entries instead. For example, Yakamara has [5 entries in Frankfurt’s Kaiserstraße](https://friendsofredaxo.github.io/community/#18,50.10775,8.66742).

If your map wants to be used by companies — not single persons — and you want them to manage multiple locations within one entry, you’ll probably need to develop the feature for yourself.
I would recommend, however, that you allow only one location per entry as we do cause it makes things easier.

**Comment by kermie** [comment]
Thank you @schuer , That was just an idea to make maintenance more comfy for those who are affected. In case we get a PR (== self developed feature) with this need and decide to merge it, I'll be happy to forward it to you guys. Happy New Year! ;)
