### ISSUE TITLE
map eintrag

### ISSUE THREAD

**Issue by rkemmere** [FriendsOfREDAXO/community#173]
Please add my entry

* nick/name: Ronny Kemmereit
* latitude: 49.832539
* longitude: 8.7504448
* personal bio: Holder of Manétage. Working with Redaxo since 2007 and I have implemented hundreds of projects with Redaxo. Core industries are the real estate, travel and tourism sectors.
* personal image: https://avatars0.githubusercontent.com/u/2286625?s=400&u=983d54dc016eb40171c8c92912c0dc0108b9a05b&v=4
* links: http://www.manetage.de

**Comment by schuer** [comment]
🎉 https://friendsofredaxo.github.io/community/#rkemmere
