### ISSUE TITLE
MyREDAXO User mit aufnehmen auf die Map + Map auf redaxo.org offen präsentieren ?

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/community#182]
Externe MyREDAXO Datenquelle mit aufnehmen (Agenturen) und diese dann anzeigen lassen ?

**Comment by schuer** [comment]
Aus meiner Sicht soll es unbedingt eine Community-Karte bleiben, also auf einzelne Menschen gemünzt, nicht auf deren Unternehmen. Und ich vermute, der MyREDAXO-Datensatz ist leider auf Unternehmen ausgerichtet, so dass er nicht für die Karte taugt?

**Comment by schuer** [comment]
Nochmal das Thema aufgegriffen: Wollen wir vielleicht auf redaxo.org unter »Agenturen« einen neuen Menüpunkt »Community« hinzufügen und auf der Seite die Community-Karte im iFrame einbetten? Dazu ein Einzeiler, was es ist, dass man sich eintragen kann sowie die passenden Links dazu?

**Comment by dergel** [comment]
wegen mir gerne :)

**Comment by staabm** [comment]
eine community seite könnte
- FOR vorstellen
- auf Slack hinweisen
- die Map enthalten

**Comment by schuer** [comment]
@staabm Es gibt bereits diese Seite: https://redaxo.org/support/ressourcen/
Aber vielleicht ist die auch schon zu voll, und man könnte alle Community-Themen ausklammern? Ich würde jedenfalls mal die Karte im iFrame anbringen und verlinken wie oben beschrieben, und dann können wir ja direkt weiter dran arbeiten. Deal?

**Comment by staabm** [comment]
klar fang erstmal an.

> Aber vielleicht ist die auch schon zu voll, und man könnte alle Community-Themen ausklammern?

ich denke das könnte gut funktionieren, ja.

**Comment by schuer** [comment]
Vorschlag: https://redaxo.org/support/community/

**Comment by staabm** [comment]
find ich super!

**Comment by schuer** [comment]
Also, übrig bleibt in diesem Issue noch der Punkt »MyREDAXO-User mit aufnehmen«. Ich denke, das sollte zum einen nicht automatisch passieren, sondern durch die User selbst. Und zum anderen sind auf MyREDAXO gerade Firmen, keine einzelnen Menschen, so dass die Daten sowieso nicht ohne Anpassung integriert werden könnten.

Close?

**Comment by staabm** [comment]
meiner Meinung nach ja: @dergel  ?

**Comment by dergel** [comment]
passt für mich
