### ISSUE TITLE
Tip: opening links in another tab, so as not to leave the map

### ISSUE THREAD

**Issue by nandes2062** [FriendsOfREDAXO/community#195]
Tip: Opening links in another tab, so as not to leave the map, with `<a href="' + link + '" target="_blank">' + linkText + '</a>` in https://github.com/FriendsOfREDAXO/community/blob/788bde7facbee9cdfb5568acb7db242a3fbea98c/assets/js/script.js#L51

**Comment by schuer** [comment]
Thx!
