### ISSUE TITLE
Please add map entry for me :)

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/community#196]
Add or update your maps entry? → Please fill out the required fields below.
Your issue relates to another topic? → Please clear this text field and enter your text.

* nick/name: Stefan Dannfald (dpf.dd)
* latitude: 51.038373
* longitude: 13.681850
* personal bio: Als gelernter Mediengestalter (Digital/Nonprint) und leidenschaftlicher Autodidakt arbeite ich seit 2007 vorwiegend und sehr gern mit REDAXO. Individuelle Module, Templates, AddOns usw. gehen gut von der Hand und sorgen für eine zuverlässige und schnelle Umsetzung aller Kundenwünsche. Ich liebe es :)
* personal image: https://ca.slack-edge.com/T1BCPLXEE-U41RYAUSJ-b086861ca1a9-512
* links: https://www.einradpioniere.de, https://github.com/dpf-dd, https://www.facebook.com/stefan.dannfald

See `_directory/.data.example.yml` for detailed instructions!

**Comment by schuer** [comment]
https://friendsofredaxo.github.io/community/#dpf-dd
