### ISSUE TITLE
Worum geht’s?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/community#2]
Olli betreibt die Website http://redaxo-entwickler.de, die nun Teil von FOR werden soll. 🎉

Aktuell läuft die Website auf Basis von REDAXO 4 mit XForm und bietet den Nutzern Formulare an, um sich einzutragen. Die enthaltenen Daten werden dann manuell geprüft und im Verzeichnis eingetragen.

Für die neue Website ist der Plan, dass sich Nutzer eigenständig eintragen und ihre Daten anschließend selbst verwalten können. Nämlich direkt innerhalb des Repos mittels Pull Requests, die wir beim mergen prüfen können, damit kein Unfug rein kommt.

Ergebnis ist dann eine von GitHub betriebene statische Website, die Teil unserer Community ist, von ihr gepflegt und erweitert werden kann, und die sogar auch andere Projekte (CMS-se oder sonstige Projekte) nutzen könnten, um ihre Entwicklerkarten mit Hausmitteln zu verwalten.

Falls wir das so machen wollen, würde ich folgenden Plan vorschlagen:

1. Wir migrieren die bestehende Website rüber zu GitHub. Ich kann das gerne übernehmen, weil ich im Zuge der FOR-Website, die sehr ähnlich aufgebaut ist, Erfahrung mit den GitHub-Jekyll-Themen gesammelt habe. Sollte kein großer Aufwand sein, weil das gesamte Frontend schon vorliegt.
2. Wir diskutieren die Datenstruktur (yml, json? Welche Felder? Welche sind required, welche optional?)
3. Wir befüllen die neue Website mit den bestehenden Daten der alten Website.
4. Wir schreiben Anleitungen, damit die Leute wissen, wie sie ihre Daten pflegen können.
5. Vielleicht bringen wir die verwendeten Komponenten (etwa Leaflet) nochmal auf den aktuellen Stand und ändern alles, was wir sonst noch ändern wollen.

Done. Wer hat Lust drauf?

**Comment by olien** [comment]
Ich mach mit ;-)

**Comment by staabm** [comment]
Wir können die aktuelle karte dann schon via iframe o.ä. auf redaxo.org integrieren (auch wenn die datenbasis erstmal bei github liegt)

**Comment by schuer** [comment]
In der Zwischenzeit gab es einige Diskussionen dazu hier in den Issues und im Slack. Gregor hat eben einen Ansatz ins Spiel gebracht, aus dem inzwischen eine Idee gewachsen ist, die ich viel spannender finde:

Wie wäre es, wenn wir wirklich nur eine schlichte Developer-Map draus machen, die wie oben beschrieben bei GitHub gepflegt wird, die aber KEIN Dienstleisterverzeichnis sein möchte. Stattdessen soll sie wirklich nur aufzeigen, wo sich REDAXO-Entwickelnde befinden, weltweit. Und sie liefert keine offiziellen Kontaktdaten und Klimbim, sondern nur wenige Infos, die für Developer interessant sind, etwa: GitHub-Account, Website, Anzahl der Jahre mit REDAXO-Erfahrung, Kurzbeschreibung der Person, die vielleicht Infos enthält, an welchen AddOns oder Projekten die Person beteiligt ist, etc.
— Reines Ziel also: Die REDAXO-Entwicklercommunity sichtbar machen, sonst nichts.

Das Dienstleisterverzeichnis — sowohl für einzelne Personen als auch Agenturen — wäre dann auf redaxo.org und kann ebenso um die Kartenfunktionalität erweitert werden, sobald die Ressourcen dafür vorhanden sind.

Beide Projekte können und sollen gerne parallel laufen, denn sie haben unterschiedliche Absichten.
Was haltet ihr davon?

**Comment by schuer** [comment]
Nochmal vereinfacht gesagt: Auf dem GitHub-Projekt soll man einfach nur ein Fähnchen auf eine Karte setzen können, wenn man was mit REDAXO macht. ¯\\\_(ツ)_/¯

**Comment by olien** [comment]
Die Idee finde ich gut!

**Comment by olien** [comment]
es könnte ja zusätzlich auf das my redaxo profil verwiesen werden...

**Comment by schuer** [comment]
Ja. Und außerdem: Jede Person kann sich einen Eintrag machen, unabhängig von der Firma, in der die Person vielleicht arbeitet. Die Y’s wären dann etwa mindestens 4 Leute auf der Map, andere Agenturen ebenso mit mehreren Leuten vertreten. Und wenn man sich mit REDAXO beschäftigt, aber keine Dienstleistung anbietet, wäre die Map auch total richtig, anders als ein Dienstleisterverzeichnis. Und man müsste z. B. auch gar nicht mit Klarnamen auftreten, wenn man nicht möchte. Nickname würde reichen.

**Comment by olien** [comment]
Dann würde ich es vielleicht wirklich wirklich viel schlanker halten.
Ein Header mit dem FOR Logo, ein Info Modal (Was, Wie, Impressum) und nur Marker (alle gleich).
Alle Infos gehen dann in einem Bootstrap Modal auf: http://gregallensworth.github.io/L.Control.BootstrapModal/

keine Suche, keine Liste... einfach nur viele tolle Marker... (im Cluster)

**Comment by schuer** [comment]
Yeah, genau so!

**Comment by olien** [comment]
TOP. GOGOGO.

Es gibt nur einem Tag an dem Du etwas erledigen kannst. HEUTE :-)

**Comment by olien** [comment]
![for_worker](https://user-images.githubusercontent.com/330516/31375634-7bb8905c-ada2-11e7-9157-4b78352ced6d.jpg)

**Comment by joachimdoerr** [comment]
Top das kommt mir ja sehr entgegen :)

**Comment by schuer** [comment]
Update, siehe #9

**Comment by schuer** [comment]
#11
