### ISSUE TITLE
For Users only ? Or Companies ? Or FOR only ?

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/community#26]
Thank dirk for your work.
But i am quiet unsure if this map ist for anyone or if there are some rules ?
regards

**Comment by skerbis** [comment]
It‘s for all developers / people,  agencies and companies should be published on redaxo.org @dergel

**Comment by schuer** [comment]
Like skerbis said: It’s for everyone — every person! — being involved in REDAXO @dergel! If someone uses REDAXO and likes to join the map, they are welcome.
(Short because sent from mobile.)

**Comment by schuer** [comment]
@dergel, now I can write in more detail: we’ve discussed the map a lot, and as a result we wanted the map to be a place for any person who’s involved in REDAXO: developers, users, editors, writers, designers, friends and family et al. It’s about visualizing the REDAXO community!

Companies and service providers already have the chance to present their portfolio at MyREDAXO on redaxo.org, but the community consists of many people who are involved in REDAXO but do not offer professional services. Even @staabm, one of the core developers, does not work on REX projects and he wouldn’t be listed in MyREDAXO. ;)
—So, the community is much bigger than we thought, and that's what we want to show.

You ask about rules: **the one and only rule to place your marker on the map should be that you use and/or support REDAXO, no matter in what way!**

🌳

**Comment by schuer** [comment]
To be clear: you Yakamara people would be at least 4 markers on the map, maybe even 6. So you’d better watch out and not place your markers too tight in the Kaiserstraße ;)

**Comment by schuer** [comment]
(Updated the [README](https://github.com/FriendsOfREDAXO/community/blob/master/README.md).)

**Comment by schuer** [comment]
Reopen if more info or action required!
