### ISSUE TITLE
Karte für Websites beibehalten?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/community#3]
Sollen auch Websites weiterhin auf der Karte gezeigt werden, oder sollen nur die Entwicklenden (Personen und Agenturen) aufgezeigt werden?

**Comment by schuer** [comment]
Ich persönlich würde die Websites ja eher weglassen.

**Comment by skerbis** [comment]
ich auch. Das wird sonst sehr unübersichtlich.

**Comment by olien** [comment]
Webseiten müssen nicht sein...
