### ISSUE TITLE
Problems with the map? / Probleme mit der Karte?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/community#33]
I thought there'd be 100 people on the map in a few days. But they're not. What's the problem? Is the GitHub workflow too difficult? Is English a language barrier? Aren't you interested in the map? ¯\\\_(ツ)_/¯

Feedback very welcome!

---

Ich hätte gedacht, dass nach wenigen Tagen 100 Leute auf der Karte sind. Sind es aber nicht. Woran liegt es? Ist der GitHub-Workflow zu kompliziert? Ist Englisch eine Hürde? Oder seid ihr nicht interessiert an der Karte? ¯\\\_(ツ)_/¯

Freue mich auf Rückmeldung!

**Comment by olien** [comment]
Ich vermute, dass der Github-Workflow die größte Hürde ist...

**Comment by alexplusde** [comment]
Ich sag dazu nichts...

**Comment by joachimdoerr** [comment]
I think it shows that the rex community is "passiv" -> even the FOR members from GitHub do not create an marker.

**Comment by staabm** [comment]
> Ich vermute, dass der Github-Workflow die größte Hürde ist...

Wenn jmd interesse hätte wurde an vielen stellen bereits mehrfach draufhin gewiesen dass gerne geholfen wird

> Ich sag dazu nichts (mehr)...

@alexplusde falls sich das auf das argument „entwickler map“ vs. „Community map“ bezieht sollte dem ja bereits sorge getragen sein.
Falls es andere argumente gibt sollte man sie vorbringen...

**Comment by alexplusde** [comment]
@staabm Meine Einschätzung: 
1. Ich denke, es ist von der Community bzw. vielen Entwicklern hier einfach zu viel verlangt, ständig etwas neues zu voten, sich daran zu beteiligen, anzuschauen, umzugewöhnen und einzuarbeiten. Bei aller Liebe zu REDAXO.
2. Aktive GitHub-Beteiligung ist für viele aus der Community ein Novum, eine Umstellung. In einer idealen Welt arbeiten wir längst alle mit Git-Versionierung, laden Redaxo nicht mehr unverschlüsselt per FTP hoch und haben Produktiv- und Testsysteme stets bereit. Gerade beim Redaxo-Tag wird doch deutlich: Die meisten stehen hier noch nicht mal in den Startlöchern, was zeitgemäße Entwicklung angeht, wenn Website-Entwicklung vlt. sogar nur einen Teil der eigenen Arbeit ausmacht (Stichwort Freelancer, Ein-Personen-Agenturen, etc.). GitHub kann man einfach nicht voraussetzen und überstülpen.
3. Die Usability des Workflows ist demzufolge auch für die Zielgruppe Mist. Mundgerecht serviert wäre ein Formular mit 5-10 Feldern, ausfüllen, abschicken, fertig. Ich habe es angeklickt, sehe die Vorlage, musste erstmal überlegen...
** ob ich da jetzt nen PR machen muss?
** Oder ne eigene Branch? 
** Hatte die Befürchtung dass wieder irgendwas nicht so funktioniert, wie es soll (weil ich nicht so fit in Git bin) 
** Habe dann gesehen, dass es auch die Möglichkeit gibt, das ganze als Issue aufzubereiten,
** darin gesehen, dass viel weniger verlangt wird an Infos, als in der Vorlage,
** mich dann gefragt, wie ich es denn nun am besten mache und...
** aufgrund der vielen Gedanken festgestellt, dass ich schon keine Lust mehr habe.
4. Ich vermute mal, es geht auch darum, dass der Vorteil nicht klar wird. Für viele ist Redaxo eben auch nur ein Werkzeug und keine Lebensphilosophie. Wenn man sich eben nicht als Teil der Community versteht und schon ein Foren-, Slack- und allgemeins GitHub-Profil hat, vlt. allgemein noch Xing, LinkedIn, etc. - wozu dann noch eine Eintragung hier?

Der Köder muss dem Fisch schmecken, nicht dem Angler, und das ist hier in meinen Augen nicht passiert.

**Comment by alexplusde** [comment]
Und, falls das nicht klar sein sollte: Ich schätze die Arbeit von euch allen ungemein, an der Stelle @schuer und @olien, das ist keine Kritik an euch. Und ich stehe auch hinter der Idee - nicht jede Idee klappt auf Anhieb, also bitte nicht das Projekt gleich in die Tonne werfen.

**Comment by polarpixel** [comment]
Bei mir selbst war es einfach Zeitmangel, kommt noch.
Generell finde ich den Workflow schon gut (danke @schuer!), wer sich bislang noch nicht mit Github & Co. beschäftigt hat, wird dazu hier vielleicht auch animiert.
Aus meiner Sicht sollte die Karte auf redaxo.org eingebunden werden (ist das noch geplant?). Denn dann werden sicher mehr Leute durch den werblichen Effekt ihren Marker setzen.

**Comment by olien** [comment]
@polarpixel Auf redaxo.org sollte eine eigene Karte m it den Agenturen aus myREDAXO eingebunden werden...

**Comment by polarpixel** [comment]
Dann könnte das Der Grund für die Zurückhaltung sein. Gedanken wie: "Warum soll ich meinen Marker setzen, wenn ich keinen Vorteil davon habe?" Community-Gefühl ist m.E. für viele nicht so wichtig, wie wir glauben.

**Comment by olien** [comment]
Das kann gut sein, selbst der myREDAXO Bereich könnte ja wesentlich mehr Einträge (als aktuell 79) haben.

**Comment by staabm** [comment]
Ich vermute es könnte später dann auch auf eine „kombo“ karte rauslaufen, d.h. Agenturen aus myredaxo + einzelpersonen wie aktuell

**Comment by joachimdoerr** [comment]
Also mir kommt diese Map wie sie hier angeboten wird total entgegen, ich will mich nicht vermarkten aber mir persönlich ist die community wichtig. Danke @schuer und @olien für das super coole Projekt.

**Comment by schuer** [comment]
Danke für das viele Feedback, vor allem auch @alexplusde für seine ausführliche Einschätzung.

Ich persönlich finde die Karte superklasse und hätte sie mir viel eher gewünscht. Wir hatten [etwa 2013 herum schonmal den Plan](https://github.com/DECAF/People-Map), mit dem Unterschied, dass wir die Daten von extern sammeln wollten. Jedes Mitglied hätte den Datensatz irgendwo auf dem eigenen Server (oder anderswo öffentlich erreichbar) hinterlegt, und die Karten-App hätte die Daten regelmäßig eingesammelt. Das war dann leider zuviel Aufwand für uns zu dem Zeitpunkt, so dass das Projekt eingeschlafen ist. Diese neue Karte hier macht das gleiche, aber viel cooler, weil alle Daten direkt bei GitHub liegen.

Ich finde die Karte vor allem deshalb so klasse, weil sie alle Community-Mitglieder gleichwertig darstellt, unabhängig davon, wie aktiv sie sind, an welchen Projekten sie arbeiten und welche Fähigkeiten sie mitbringen. Alle bekommen den gleichen Marker und die gleiche Chance, zu zeigen, dass sie Teil der Gemeinschaft sind.

Und auch außerhalb der Community ist die Karte nicht unwichtig, weil sie vermittelt, wo auf der Welt REDAXO eingesetzt wird. Wir mussten neulich bei Wikipedia belegen, dass REDAXO vor allem im deutschsprachigen Raum eingesetzt wird, und haben keine guten Belege dafür gefunden. Am Ende musste irgendein Artikel aus der PC-Welt oder sowas herhalten, der mehrere Jahre alt war, und der nur deshalb taugte, weil dieser eine Satz drin stand. Unsere Karte könnte sowas zukünftig viel besser belegen, weil sie allen — vor allem auch Nicht-deutschsprachigen — die Chance bietet, ein Fähnchen zu setzen.

@alexplusde, ich kann auch voll verstehen, dass GitHub eine Hürde ist. Manche Leute haben nichtmal einen GitHub-Account. Aber ich finde, Git ist schon lange ziemlich unersetzlich für Webentwicklung (speziell GitHub für Open-Source), und vielleicht kann diese Karte sogar helfen und motivieren, auf den Zug aufzuspringen. Wir haben schon soviel geschafft im REDAXO-Umfeld und helfen uns so viel gegenseitig, da sollten wir doch wohl nicht an dieser simplen Karte scheitern!

**Comment by olien** [comment]
Und wenn wir (_wir_.. haha. Du :-)) doch noch ein Formular bauen?
Die Daten kann ich auch gerne eintragen...

**Comment by olien** [comment]
Ich kann auch diese Woche mal alle anschreiben die sich auf redaxo-entwickler.de eingetragen haben...

**Comment by olien** [comment]
Wobei da ja der Fokus bei redaxo-entwickler.de darauf liegt, dass jemand REDAXO Entwickler finden kannte. Soweit ich weiß gab es über diese Kare auch einige qualifizierte Kundenkontakte. Hier fehlen halt die Firmen und ich glaube an der Stelle wird evtl. die Idee nicht verstanden... Später gibt es zwei Karten... auch schwer zu verstehen... Vielleicht gibt es doch noch Platz für Agenturen, Freelancer, Einzelkämpfer und interessierte Bastler? Aber die Diskussion hatten wir ja schon...

**Comment by staabm** [comment]
> Wobei da ja der Fokus bei redaxo-entwickler.de darauf liegt, dass jemand REDAXO Entwickler finden kannte. Soweit ich weiß gab es über diese Kare auch einige qualifizierte Kundenkontakte. Hier fehlen halt die Firmen und ich glaube an der Stelle wird evtl. die Idee nicht verstanden... Später gibt es zwei Karten... auch schwer zu verstehen... Vielleicht gibt es doch noch Platz für Agenturen, Freelancer, Einzelkämpfer und interessierte Bastler? Aber die Diskussion hatten wir ja schon...

wenn du in der mail die idee erklärst könnte das klappen. ich denke man könnte anführen dass redaxo-entwickler.de einen "nachfolger" hat und dort nun "alle nutzer" von redaxo drauf sollen.
(evtl könntest du ankündigen dass redaxo-entwickler.de in der form wie es heute ist nicht mehr länger exisitieren wird - falls das so für dich passt und der realität entspricht)

minimalziel wäre von den leuten ein "ok" zu bekommen um sie mit den gleichen daten von redaxo-entwickler.de in die community seite zu übernehmen.

**Comment by olien** [comment]
Passt für mich (selbstverständlich) und wird der Realität entsprechen... Ich denke mir mal mit @schuer etwas aus wenn er mag :-)

**Comment by schuer** [comment]
> Und wenn wir (wir.. haha. Du :-)) doch noch ein Formular bauen?

@olien Das hatte @staabm auch schonmal intern vorgeschlagen. Kann man technisch machen, würde dann aber extern in einer Umgebung mit Backend laufen müssen. Hier bei GitHub klappt’s nicht.
Ich persönlich habe leider nicht viel Lust drauf, sowas zu bauen. Aber wenn jemand mag, klar, warum nicht!

`redaxo-entwickler.de` würde ich übrigens nicht allzu bald abschalten. Lieber einen Hinweis auf die Community-Karte in dem Layer anbringen, wo beschrieben wird, wie man einen Eintrag hinzufügt. Denn wie du schon sagst: redaxo-entwickler.de hat schon einige Kontakte vermittelt. Würde ich persönlich erst abklemmen, sobald eine neue Lösung auf redaxo.org integriert worden ist.

**Comment by alexplusde** [comment]
> und vielleicht kann diese Karte sogar helfen und motivieren, auf den Zug aufzuspringen.

Wunschdenken, dass sich Nutzer etwas aufzuzwingen lassen, indem man es schwieriger macht.

**Comment by schuer** [comment]
> Wunschdenken, dass sich Nutzer etwas aufzuzwingen lassen, indem man es schwieriger macht.

Naja, wir haben das ja hier nicht mutwillig schwierig gemacht. Und es soll auch niemand gezwungen werden. Wer Lust hat, macht mit, wer nicht, nicht. Und wer Hilfe benötigt, meldet sich gerne auf diversen Kanälen.

Sogar die technische Lösung für das Formular zum Eintragen existiert bereits. Sie nennt sich E-Mail und wird an _friendsof [at] redaxo.org_ gesendet.

Eins noch zum Thema Wunschdenken: Weißt du, wie aufwendig es ist, aktiv an Wikipedia teilzunehmen? Man muss einen Account anlegen, die Verhaltensregeln lernen, das komische Wiki-Markup lernen, über Lizenzen für Screenshots nachdenken, sich neutrale Sprache aneignen, haufenweise Belege sammeln und noch so viel mehr. Der REDAXO-Eintrag neulich hat mich absurd viel Zeit gekostet.
Und dennoch funktioniert Wikipedia. Offenbar gibt es genug Menschen, die die Motivation aufbringen können, aktiv am Projekt teilzunehmen. Warum sollte das nicht auch bei unserer Community-Map funktionieren?

**Comment by alexplusde** [comment]
Weil Redaxo nicht Wikipedia ist. Nicht alles, was hinkt, ist ein Vergleich. Ich klinke mich hier mal aus der Diskussion aus.

**Comment by schuer** [comment]
Ich wollte auch nicht REDAXO und Wikipedia vergleichen, sondern auf die Motivation hinweisen, die beide Projekte dringend benötigen. Sie ist alles.

Und jetzt hoffe ich einfach weiter darauf, dass Leute motiviert werden, sich auf unserer Community-Karte einzutragen, dass Sie GitHub ausprobieren, wenn sie es noch nicht gemacht haben, und dass sie sich melden und Hilfe von uns bekommen, wenn mal was klemmt.

**Comment by staabm** [comment]
Ich denke wir können das issue jetzt so abschließen.... sind ja einige leute heute dazugekommen.
