### ISSUE TITLE
Daten ändern ...

### ISSUE THREAD

**Issue by royalemotions** [FriendsOfREDAXO/community#336]
Hallo zusammen,

ich habe meine Website von .de auf .com umgestellt und somit in der World Map das Bild nicht mehr drin.
Außerdem sollte man da royalemotions.de auf royalemotions.com ändern.

Bild liegt hier: https://www.royalemotions.com/special/regina3_profil.jpg

Kann mir das jemand machen? Das wäre voll super! :)

Beste Grüße
Regina

**Comment by schuer** [comment]
https://friendsofredaxo.github.io/community/#royalemotions

Viele Grüße! 👋

**Comment by royalemotions** [comment]
Danke! 👍😊

Beste Grüße
Regina Meissner

royal emotions - stay digital
Grabenstr. 4
73033 Göppingen

***@***.***
www.royalemotions.eu
07161 29 00 905
0175 333 99 13
