### ISSUE TITLE
User „profil“ urls

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/community#37]
man könnte auch user urls machen, damit die map mit focus und bissl umkreis um eine person intial rendert. /community/staabm als user url, wie z.b. Bei github

Die karte kommt dann zentriert zur person und öffnet auch intial schon das overlay zum user.
Man sollte um die person herum bissl umkreis der landkarte sehen um ggf. Weitere personen „direkt entdecken“ zu können

**Comment by schuer** [comment]
Top! Das sollte relativ einfach machbar sein.

**Comment by schuer** [comment]
Ich weise es mir mal zu, denn ich hatte gestern abend schon ein bisschen dran rumgebaut. Wenn ich heute abend Zeit finde, mache ich es fertig.

**Comment by staabm** [comment]
cool 😍

**Comment by schuer** [comment]
Wird zusammen mit #49 implementiert.
