### ISSUE TITLE
Onboarding: mehr information im first view

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/community#39]
Wenn man das projekt nicht kennt und die seite besucht, sieht man zunächst einmal eine weltkarte mit paar nadeln drin.

Ein paar mehr infos was man gerade sieht wären für neu besucher hilfreich.

Man könnte entweder generell irgendwo bissl text hinpacken (also für alle besucher).
Alternativ könnte man auch beim 1st (oder den ersten paar) Visit(s) einen layer aufpoppen - realisierbar z.B. via LocalStorage JS Api

**Comment by schuer** [comment]
Klasse Idee! Ich würde vorschlagen, den vorhandenen Info-Layer beim ersten Besuch initial anzuzeigen. Was meint ihr?

**Comment by olien** [comment]
Ja. Idee finde ich gut
