### ISSUE TITLE
E-Mail und Telefon speichern?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/community#4]
Wenn die Daten bei GitHub gepflegt werden, sind sie zwangsläufig öffentlich. Grundsätzlich kein Problem, denn man trägt sich ja auch in ein öffentliches Entwicklerverzeichnis ein. Allerdings sind solche Daten bei GitHub deutlich einfacher auffindbar und automatisiert crawlbar als in einer geschlossenen REDAXO-Installation.

Deshalb die Frage: Wollen wir Kontaktdaten wie E-Mailadresse und Telefonnummer weiterhin verwenden, oder aus Datenschutzgründen lieber weglassen und stattdessen die Nutzer einen Kontaktlink angeben lassen, der beispielsweise auf die Kontaktseite ihrer Website zeigt?

Falls wir die Daten beibehalten, sollten wir die E-Mailadressen meiner Meinung nach in zwei Teilen speichern, den Teil vorm @ und den Teil nach dem @, und dann bei der Ausgabe zusammenbauen, ggfls mit Obfuscator-Funktion. Die Telefonnummer könnte man ebenso in zwei Teilen speichern, Vorwahl und Nummer.

**Comment by staabm** [comment]
Ich würde die daten zumindest optional machen.. aber man kann sie aich ganz weglassen

**Comment by olien** [comment]
Und übrigens... 

Ich würde mit komplett neuen Daten anfangen. So hat jeder die Möglichkeit die Daten anzugeben die er mag. Wir haben nochmals die Möglichkeit angegebene Daten zu prüfen (ich habe viele Einträge bekommen die nichts mit REDAXO zu tun hatten). 

Für Leute die keinen Github Account haben (wollen) können wir evtl. trotzdem noch ein Formular machen welches die Daten dann an mich schickt. Ich trage die dann weiterhin ein...

**Comment by tbaddade** [comment]
> Für Leute die keinen Github Account haben (wollen) können wir evtl. trotzdem noch ein Formular machen welches die Daten dann an mich schickt.

Würde ich nicht machen. Ohne GH Account kein PR -> kein Eintrag.

**Comment by olien** [comment]
Das würde zumindest eine gewisse Affinität zur Materie gewährleisten :-)

**Comment by tbaddade** [comment]
Bzw. was würde die Leute mit Account davon abhalten, dir ebenfalls die Daten zu schicken. So frei nach: "Der Oli macht das schon". ;)

**Comment by schuer** [comment]
Es ist ja eine Developer-Map, insofern könnte man schon voraussetzen, dass zumindest ein GitHub-Account vorhanden ist, wenn sich Leute eintragen wollen. Ich würde aber die Latte insofern etwas tiefer ansetzen, indem wir den Leuten auch ermöglichen, Issues mit der Bitte um Eintragung statt eines PRs zu erstellen. Denn wie @alexplusde anmerkte: Nicht jeder ist vielleicht so richtig github-affin und traut sich PRs in einem Community-Projekt zu, bei dem einige Leute dabei zuschauen.

Aber Formular würde ich nicht machen, ist technisch bei GitHub auch gar nicht möglich. Allenfalls eine Art Notfall-E-Mailadresse anbringen, die dann vermutlich die allgemeine FOR-Adresse wäre.

**Comment by olien** [comment]
Findet Ihr die Trennung Agentur / Einzelkämpfer gut? Soll es weiterhin unterschiedliche Marker geben?

Ich würde es fast nicht mehr machen. Vielleicht kann es ein Feld für Unternehmensgröße (Anzahl d. Mitarbeiter) geben? Ich glaube nicht, dass es möglich ist die Qualität der Leistung dadurch zu bewerten... (war meine Ursprüngliche Idee).

**Comment by schuer** [comment]
Stimmt schon, aus Qualitätssicht bräuchte man eigentlich nicht zwischen Person und Team trennen. Dann könnten wir vielleicht wirklich besser ein Feld »Anzahl der REDAXO-Entwickelnden« (als Integer) oder sowas machen und einen schlichten Filter im Frontend bereitstellen wie: 1, 2–4, 5–10, >10.

**Comment by olien** [comment]
Filter... kann muss nicht... mir egal :-)

**Comment by alexplusde** [comment]
> Aber Formular würde ich nicht machen, ist technisch bei GitHub auch gar nicht möglich. Allenfalls eine Art Notfall-E-Mailadresse anbringen, die dann vermutlich die allgemeine FOR-Adresse wäre.

Genau das meinte ich. Jetzt haben wir eine technische Lösung. != praktikable anwenderfreundliche Lösung.

**Comment by staabm** [comment]
> Genau das meinte ich. Jetzt haben wir eine technische Lösung. != praktikable anwenderfreundliche Lösung.

aktuell hängt es nur an oli alleine und das ist viel schlimmer.

**Comment by olien** [comment]
Na danke.... :-)

**Comment by schuer** [comment]
Schaut mal gerade, hier gibt es vielleicht Neues zum Thema: https://github.com/FriendsOfREDAXO/redaxo-entwickler.github.io/issues/2#issuecomment-335155673

**Comment by schuer** [comment]
Dieses Thema kann sicherlich nun geschlossen werden.
