### ISSUE TITLE
ROYALEMOTIONS > Mapeintrag

### ISSUE THREAD

**Issue by royalemotions** [FriendsOfREDAXO/community#43]
Add or update your maps entry? → Please fill out the required fields below.
Your issue relates to another topic? → Please clear this text field and enter your text.

* name: royal emotions - stay digital
* latitude: 48.70358
* longitude: 9.6485
* bio: Passionated female webdesigner, successful self-employed since 2006 and love to work with customers on a high-level partnership and also with agencies an other dudes out of the field of web and digital design.
* image: http://www.royalemotions.de/regina3_profil.jpg
* links: www.royalemotions.de

See `_directory/.data.example.yml` for detailed instructions!

**Comment by royalemotions** [comment]
Maybe additional my name: Regina Meissner, after the name of the company

**Comment by schuer** [comment]
Maybe your real name only without company?

**Comment by royalemotions** [comment]
:D Die meisten kennen mich mit unter royalemotions, daher beides wäre gut

**Comment by royalemotions** [comment]
Was arbeitest Du Sonntags?

**Comment by schuer** [comment]
Das ist keine Arbeit, sondern Spaß :)

**Comment by royalemotions** [comment]
Stimmt. ich mache heute noch Buchhaltung ... :(

**Comment by schuer** [comment]
Done 🙌

**Comment by royalemotions** [comment]
Yippiee!

**Comment by royalemotions** [comment]
Sorry, habe eben gesehen, dass ein "d" fehlt ... and other dudes

**Comment by schuer** [comment]
Korrigiert.
