### ISSUE TITLE
Redaxo.org news schreiben

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/community#48]
Das projekt in einer redaxo.org news beschreiben/erwähnen/bewerben

**Comment by schuer** [comment]
Bin dran

**Comment by schuer** [comment]
Textvorschlag, bitte um Feedback @polarpixel @dtpop @dergel @staabm:

---

# Weltkarte der REDAXO-Community

Die Community wächst stetig, wir merken es an den inzwischen über 300 Mitgliedern im [Slack-Chat](https://redaxo.org/slack/), der Aktivität bei GitHub, Facebook und Twitter, und nicht zuletzt an den REDAXO-Tagen, bei denen neben bekannten Gesichtern immer wieder auch Neue auftauchen. Gerade bei den Treffen vor Ort wird immer gefragt: _Woher kommt ihr? Wer hatte die weiteste Anreise?_

Um besser aufzeigen zu können, wo überall auf der Welt Menschen mit REDAXO zu tun haben, gibt es nun diese Karte, auf der sich alle eintragen können: Entwickelnde, Designerinnen, Texter, Administratorinnen, Anwender und alle, die REDAXO in irgendeiner Form verwenden oder unterstützen. Wenn du mit REDAXO zu tun hast, bist du herzlich eingeladen, Teil der Community-Karte zu werden!

https://friendsofredaxo.github.io/community/

Neben der Lokalisierung geht es auch darum, der Community Aufmerksamkeit zu schenken. Jede einzelne Person soll sichtbar werden, unabhängig davon, wie aktiv sie ist, an welchen Projekten sie arbeitet und welche Fähigkeiten sie mitbringt. Alle bekommen den gleichen Marker und die gleiche Chance, zu zeigen, dass sie Teil der Gemeinschaft sind.

Es gibt drei Möglichkeiten, einen Eintrag hinzuzufügen oder einen bestehenden Eintrag zu bearbeiten:

1. Sende einen Pull Request bei GitHub  
Das ist die beste Möglichkeit für alle, die Erfahrung mit GitHub haben: Erstelle einen Fork des [Repos](https://github.com/FriendsOfREDAXO/community), ergänze deinen Eintrag und gebe ihn mittels Pull Request zurück. Nachdem er gemerged wurde, erscheint er unmittelbar auf der Karte.

2. Erstelle ein Ticket/Issue mit deinen Daten
Diese Möglichkeit eignet sich für alle, die zwar einen GitHub-Account, aber wenig Erfahrung mit Forks und Pull Requests haben: [Öffne ein Issue](https://github.com/FriendsOfREDAXO/community/issues) mit deinen Daten, dann wird sich jemand darum kümmern, den Eintrag auf die Karte zu bringen.

3. Kontaktiere uns
Wenn du keinen GitHub-Account hast oder dich mit den beiden vorher genannten Möglichkeiten unwohl fühlst, sende uns einfach eine E-Mail mit deinen Daten an _friendsof [at] redaxo.org_, und wir kümmern uns um deinen Eintrag!

Um welche Daten geht es denn eigentlich? Neben deinem Namen und deinen Standortdaten kannst du noch eine Kurzbeschreibung und Links auf deine Websites angeben. Alle Infos findet ihr bei GitHub: [How to add and manage your entry](https://github.com/FriendsOfREDAXO/community/tree/master/_directory)

(Die Karte ist übrigens englischsprachig, weil sich REDAXO gerne etwas für Menschen öffnen möchte, die kein Deutsch sprechen. Solltest du deinen Eintrag lieber auf Deutsch oder in einer anderen Sprache verfassen wollen, ist das aber kein Problem.)

**Comment by staabm** [comment]
find ich super.

**Comment by schuer** [comment]
Danke @staabm. Die News werden vor allem von @polarpixel betreut, deshalb warten wir am besten noch auf seine Rückmeldung, bevor die Meldung online geht.

**Comment by schuer** [comment]
Ich bin zu ungeduldig und haue das jetzt raus. :) Möchte den Schwung von gestern mitnehmen.
Kann ja hinterher nochmal korrigiert werden bei Bedarf.

**Comment by schuer** [comment]
https://redaxo.org/cms/news/weltkarte-der-redaxo-community/

**Comment by polarpixel** [comment]
Ich war den ganzen gestrigen und heutige Tag unterwegs, sorry @schuer.
Aber ich finde den Text super, ich hätte nichts zu verbessern gehabt.
Vielen Dank, ist toll geworden!

**Comment by schuer** [comment]
Prima, danke @polarpixel!
