### ISSUE TITLE
Domain einrichten

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/community#5]
Wie? Als normale Weiterleitung?

**Comment by staabm** [comment]
https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by schuer** [comment]
Ich glaube, mit der neuen Ausrichtung des Projekts ist die aktuelle URL leider obsolet geworden, sorry :-/

**Comment by olien** [comment]
Warum sorry? Alles gut!
