### ISSUE TITLE
share in tweet/facebook

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/community#58]
a share button on the map so people can share their experience with redaxo in social networks.

the text for the tweet/post could just be pre-filled with the "bio" + some hash-tags or similar. this way its a individual post and not generic template text.

![grafik](https://user-images.githubusercontent.com/120441/32503060-8ea0d940-c3dc-11e7-86a4-d693bdbd2584.png)

**Comment by staabm** [comment]
@schuer opinions?

**Comment by schuer** [comment]
Feature requires #37 and (maybe) #49.

I’m not sure about the sharing topic. Could be either a nice feature or too much bloat. ¯\\\_(ツ)_/¯ 
Think I’m 40% pro and 60% contra. But let’s hear from other community members!

**Comment by staabm** [comment]
People can share the „deep link“ to their user profile.

Thats enough for now
