### ISSUE TITLE
Maps entry

### ISSUE THREAD

**Issue by internetmacher** [FriendsOfREDAXO/community#59]
* name: Manuel Schmöllerl
* latitude: 48.210033
* longitude: 16.363449
* bio: Hi, I am an austrian webdesigner and I am using REDAXO since 3.x
* image:
![_schmoellerl-webonsulting-quadratisch](https://user-images.githubusercontent.com/33459847/32503592-ee6e97ee-c3dd-11e7-8aa5-dcfa133e6f34.jpg)

* links:
- https://internetmacher.at
- https://twitter.com/internetmacher

See `_directory/.data.example.yml` for detailed instructions!

**Comment by schuer** [comment]
Willkommen! 🎉
