### ISSUE TITLE
Domain Besitzer / Impressum

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/community#6]
Soll ich das sein / bleiben oder wollt ihr das übernehmen @dergel?
(Ist mir gleich)

**Comment by schuer** [comment]
Zur Info, die aktuelle GitHub-URL ist: https://friendsofredaxo.github.io/community/
Falls wir eine neue (eigene) Domain registrieren wollen, kein Problem.

**Comment by schuer** [comment]
Achso, Stichwort Impressum. Aktuell steht dies drunter:

> Legals: This service is provided by the REDAXO community which is represented by Yakamara Media.

Gut so? @dergel 
Können wir sonst gerne anpassen wie gewünscht und z. B. Olli einsetzen.

**Comment by dergel** [comment]
ich finde alle Varianten gut :)

**Comment by olien** [comment]
Ist mir eigentlich auch gleich...
Da über diese Karte tja REDAXO-Entwickler gefunden werden können würde die Domain ja passen...

(muss nicht unbedingt irgendwo erwähnt werden...)

**Comment by schuer** [comment]
Dann lassen wir doch einfach die Impressumsangaben so schlicht, wie sie gerade sind.

@olien wegen Domain: Klar, kannst du umleiten und weiter verwenden. Passt nur nicht mehr so richtig perfekt, weil deutschsprachig auf auf Entwickler bezogen. Aber technisch kein Problem, einfach umleiten.

**Comment by olien** [comment]
Dann hebe ich die Domain noch auf..
die könnte ja - auf Wunsch - jederzeit zur freien Verwendung zu yakamara wandert oder mir fällt noch etwas ein :-)

**Comment by schuer** [comment]
Wegen Domain nochmal: Lasst uns vielleicht erstmal loslaufen jetzt bei GitHub und schauen, wie es sich entwickelt, oder? Dann kann dieses Ticket geschlossen werden und es sind keine mehr offen.

Bereit für einen frischen Start. Fügt jetzt mal alle eure Marker hinzu! 🚀🙋‍♂️
