### ISSUE TITLE
Michael Hut existiert nicht?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/community#65]
Die URL ist ungültig

**Comment by schuer** [comment]
Hm, his GitHub account has been deleted. Maybe let’s wait for some days and try to reach him via Slack to check back if he wants to remove his map entry as well.

**Comment by phoebusryan** [comment]
@olien hat ihn wohl vertrieben:
https://github.com/olien/rex_focuspoint/issues/16

**Comment by olien** [comment]
Ich wollte nur nett sein.... :-(

**Comment by staabm** [comment]
in meinen augen kann der eintrag trotzdem drinnen bleiben, ist ja kein fake eintrag.

wir haben ihn ja alle gesehen.

@schuer  ich würde hier das issue zu machen

**Comment by schuer** [comment]
Ja, stimmt schon. Close.

**Comment by mhut47** [comment]
Alles gut. Ich hatte den Account nicht bestaetigt. Die E-Mail kam nicht durch die Spamfilter ;-)
