### ISSUE TITLE
Zweisprachig

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/community#78]
Ich begrüße es sehr, Redaxo außerhalb des deutschprachirgen Raums zu verbreiten, aber die Infos ausschließlich in englisch anzubieten ist vielleicht etwas übers Ziel hinausgeschossen oder? Meiner Meinung "belohnen" alle nicht-deutsch sprechenden User und "bestrafen" die deutschsprachigen User. Außerdem wirken ausschließlich englische Texte von einer deutschen Community so ein bisschen "möchtegern-international". Können wir nicht bio-de: und bio-en anbieten und das ganze dann mit einer HR trennen?

**Comment by schuer** [comment]
Danke für dein Feedback!

Die Bio können alle gerne nach Belieben ausfüllen, also in einer Sprache ihrer Wahl. Ich denke nicht, dass wir mehrere Felder dafür benötigen, sondern stattdessen die kreative/chaotische Lösung verwenden: Alle machen, was sie wollen ;)

Generell ist das kein ganz einfaches Thema mit der Mehrsprachigkeit. Für diejenigen, die nicht oder nicht so gut Englisch sprechen, macht man die Sache komplizierter, wenn man es nur auf Englisch anbietet. Aber das soll keine Bestrafung sein, sondern es bleibt ganz einfach keine andere Möglichkeit, wenn man das Projekt für alle öffnen möchte. Und die Karte ist nun ein sehr dankbares Thema, denn sie erfordert nicht viel außer ein paar wenigen Angaben von Leuten, um ein Profil einzurichten. Wollten wir komplexere Themen wie die Dokumentation für alle öffnen, würde das sehr viel anstrengender. Die Karte ist easy-peasy ;)

Lange Rede: Die Karte ist ein guter Einstiegspunkt für Nicht-Deutschsprachler, und die Chance wollten wir nutzen. Dass alle Infotexte nur auf Englisch vorliegen, liegt eigentlich nur daran, dass sie noch niemand übersetzt hat, und dass es das Projekt sehr voll (im Sinne von zuviel Text) machen würde. Stattdessen habe ich persönlich mich immer damit beholfen bisher, dass ich an ganz vielen Stellen auf Deutsch über die Karte geschrieben habe, etwa in den REDAXO-News, auf Twitter, im Forum, u. a.

Ich hoffe einfach, dass alle deutschsprachigen Nutzer unter uns — also beinahe die komplette Community — mit den englischsprachigen Texten zurecht kommt und wir uns bei Bedarf gegenseitig helfen. Oder Hilfsmittel wie [DeepL](https://www.deepl.com/translator) nutzen. Wichtig ist nur, dass wir uns für andere öffnen, sonst bleiben wir dauerhaft unter uns :)

**Comment by marcohanke** [comment]
Ich weiß ja, dass es keine „Strafe“ ist. Wenn ich mit meinen Kunden über solche Sachen rede verdeutliche ich es immer so um zu zeigen, dass wenige einen Nutzen haben, dafür aber viele ein Nachteil. Ollis alte Karte war für mich immer ein Argument für kritische Neukunden. Aussagen wie "Redaxo kenne ich nicht, wer macht das weiter wenn du vom Zug überfahren wurdest“ konnte ich damit immer entkräften. Ich find’s irgendwie eigenartig wenn alles auf englisch ist und neue Kunden/Entwickler/Freunde stellen sich vermutlich als erstes die Frage: Spreche ich XY jetzt englisch an, oder kann er deutsch ;-)

**Comment by staabm** [comment]
@marcohanke du kannst deinen kunden weiterhin auf olis karte verweisen. für den kunden sind andere entwickler sowieso interessanter als die ganze community (wo auch anwender, designer etc. drinnen stehen)

**Comment by marcohanke** [comment]
Ach, wird es die weiterhin parallel geben? Dann habe ich da was Missverstanden ...

**Comment by olien** [comment]
Die Karte gibt es (von mir aus) so lange bis alles zu redaxo.org wandert...

**Comment by staabm** [comment]
> Ach, wird es die weiterhin parallel geben? Dann habe ich da was Missverstanden ...

die 2 karten haben unterschiedliche zielgruppen und verfolgen unterschiedliche ziele.

**Comment by schuer** [comment]
Okay, dann close, oder? Sonst gerne wieder öffnen.
