### ISSUE TITLE
Repo Name

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/community#79]
Mich persönlich hat der Name community ganz kurz verwirrt. Dort erwartet man doch sowas wie die ycommunity? Macht community-world-map nicht mehr Sinn?

**Comment by tbaddade** [comment]
Alternative: Fan Club > FC Redaxo

**Comment by schuer** [comment]
Der Name sollte möglichst kurz sein, weil der Teil davor in der URL schon recht lang ist. Eigentlich war `community-map` geplant, aber dann kam die Überlegung, dass am Ende vielleicht gar nicht mehr nur eine Map unter der Adresse erreichbar sein könnte, sondern sich noch andere Dinge entwickeln. ¯\\\_(ツ)_/¯

**Comment by marcohanke** [comment]
Ich sehe, ihr habt euch ausnahmsweise wie immer schon Gedanken gemacht ;-)

**Comment by schuer** [comment]
Close? Sonst gerne wieder öffnen.
