### ISSUE TITLE
Weitere Vorgehensweise!?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/community#8]
Hier einmal meine Ideen zur weiteren Vorgehensweise.

- von der bestehenden redaxo-entwickler.de muss meiner Meinung nach nichts übernommen werden
- neue github Seite auf Basis von http://bmcbride.github.io/bootleaf/ erstellen (es sei denn es gibt etwas "besseres")
- FOR "gerechte" Inhalte schreiben
- Daten Implementierung bauen / Workflow beschreiben
- Daten eintragen (lassen)
- sofern einige (20?) Datensätze vorhanden sind Domain umziehen
- Werbung machen :-)

Wäre das eine (grobe) mögliche Vorgehensweise oder habe ich etwas vergessen?

**Comment by olien** [comment]
Das würde (mir) schon fast reichen: 

https://github.com/Leaflet/Leaflet.markercluster   in Verbindung mit
https://github.com/gregallensworth/L.Control.BootstrapModal

Fehlt nur ne Suche und ne Liste

**Comment by schuer** [comment]
Ich hatte mir Bootleaf neulich angeschaut, und es würde schon taugen. Ist leider etwas in die Jahre gekommen und wird offenbar nicht mehr so richtig gepflegt. Jemand schrieb in den Issues, dass es nur mit dem alten Leatflet 0.7 funktioniert, nicht mit dem aktuellen 1.0-Strang. Das lässt sich aber wohl halbwegs gut fixen, schrieb die Person, nur hat es der Bootleaf-Autor bisher noch nicht gemacht.
Abgesehen davon ist es aus Frontend-Sicht etwas chaotisch, aber es funktioniert.

Meine Erkenntnis war danach: Neu machen wäre schön und gar nicht irre viel Aufwand, allerdings wäre es noch schneller und einfacher, lieber die aktuelle Implementierung auf redaxo-entwickler.de vollständig zu übernehmen. Aber das willst du nicht unbedingt, @olien?

Falls wir es neu machen: Ich kann mich gerne darum kümmern, dass die Daten aus dem Verzeichnis ins HTML kommen. Und jemand anderes — du, Olli —, kümmert sich um ein neues Frontend?

**Comment by schuer** [comment]
Zum Thema Daten: Ich hatte eigentlich gedacht, die bestehenden Daten zu übernehmen. Aber klar, man könnte auch neu durchstarten und hätte damit zum einen eine sauberere Datenbasis, und man würde zum anderen sehen, ob der GitHub-Workflow funktioniert. Wenn nicht, behält man vielleicht lieber die alte Seite bei ;)

**Comment by olien** [comment]
@schuer Selbstverständlich können wir die bestehende Seite einfach übernehmen. Da habe ich nichts gegen. Fand die nur etwas eingestaubt :-). Wie auch immer... Mach Du wie und was Du magst und ich mache das Frontend FOR-Like. Bei den Texten bräuchte ich dann noch Hilfe.

Datentechnisch neu starten fände ich sinnvoll...

**Comment by schuer** [comment]
#11
