### ISSUE TITLE
Interweave Media

### ISSUE THREAD

**Issue by interweave-media** [FriendsOfREDAXO/community#80]
Add or update your maps entry? → Please fill out the required fields below.
Your issue relates to another topic? → Please clear this text field and enter your text.

* name: Jürgen Weiss
* latitude: 57.3314309
* longitude: 14.7892631
* bio: Hej, i am an german grafik an webdesigner, living in Sweden, and using redaxo since 3.x
* image: 
![che](https://user-images.githubusercontent.com/16902827/32618543-59059c74-c578-11e7-9664-25d084a75add.png)

* links: http://interweave-media.se

See `_directory/.data.example.yml` for detailed instructions!

**Comment by schuer** [comment]
🎉
