### ISSUE TITLE
Günstigsten Ort für den REDAXO Tag ermitteln... :-)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/community#87]
Aufgrund der Positionen der Marker

**Comment by schuer** [comment]
Es sollten sich vor allem noch viel mehr Leute eintragen. Wir sind >300 im Slack und fast 5.000 im Forum. Wo bleibt ihr alle? :)

Bis Nikolaus 100, klappt das? https://twitter.com/REDAXO/status/930049923101405184

**Comment by tbaddade** [comment]
> Es sollten sich vor allem noch viel mehr Leute eintragen. 

Ggf. im Slack einen Aufrufen machen, dass auch im Slack für eine gewisse Zeit die Daten übermittelt werden können. Sozusagen gänzlich ohne Github.

**Comment by schuer** [comment]
Für alle, die vielleicht noch zögern, weil sie vielleicht schon länger nichts mehr mit REDAXO gemacht haben oder sich aus anderen Gründen nicht als wichtiger Bestandteil der Community zählen: Habt bitte keine Scheu! Wer im Slack ist, ist Teil der Community. Wer sich REDAXO verbunden fühlt, ist Teil der Community. Wer Teil der Community ist, gehört auf die Map! :)

**Comment by staabm** [comment]
Ich glaube dass bei Facebook mal nen post dazu rein sollte.. dort haben wir auch viele follower und die sind vermutlich auch nicht so inaktiv wie im slack (ich gehe davon aus das im slack die meisten user nur einmalig den raum betreten haben und das chat nicht regelmäßig öffnen)

**Comment by schuer** [comment]
Ergänzend zu @tbaddade s Kommentar oben: Einfach mal die Leute im Slack direkt ansprechen (DM) und ihnen beim Map-Eintrag helfen. Ich bin gerade nicht im Slack, deshalb kann ich bei dem Thema nicht helfen, aber wir sind so viele Aktive, dass wir die Map eigentlich ruckzuck voll bekommen sollten.

**Comment by schuer** [comment]
Zurück zum Issue-Thema: Aktuell sind die REDAXO-Hotspots Frankfurt und Zürich. Aber wir haben auch erst 50 Leute auf der Map.

Willst du das Issue beibehalten, @olien? Die Planungen für den REDAXO-Tag laufen ja bereits im Slack, so dass wir hier nun schließen könnten, oder?

**Comment by olien** [comment]
Nein. Kann zu. war auch nicht so megaernst gemeint. irgendwann sollten wir eine linie von allen markern zu yakamara ziehen und dann noch linien zwischen den markern der personen die sich pers. kennen oder zusammenarbeiten :-)
