### ISSUE TITLE
Maps entry - Marc Bodon

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/community#88]
Add or update your maps entry? → Please fill out the required fields below.
Your issue relates to another topic? → Please clear this text field and enter your text.

* name: Marc Bodon
* latitude:48.7703572
* longitude:9.1797545
* bio: I'm a graphic designer from Stuttgart and redaxo user since 2007.
![marc-bodon](https://user-images.githubusercontent.com/2822717/32776791-011b8c7a-c934-11e7-9a0e-432806d9b47e.jpg)

* image: siehe dateiupload
* links: www.bodon.de

See `_directory/.data.example.yml` for detailed instructions!

**Comment by schuer** [comment]
🎉
