### ISSUE TITLE
Live Update / Tracking der User

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/community#91]

**Comment by schuer** [comment]
Kannst du genauer erklären, worum es geht?

**Comment by tbaddade** [comment]
Ich bin die nächsten Tage in Frankfurt und da wäre es hübsch den Marker via "Telefon" zu verbinden.
Weiß nicht wirklich ob das überhaupt sinnvoll ist. Ist nur so eine Idee.

**Comment by staabm** [comment]
verbinden mit was?

**Comment by schuer** [comment]
Ah, schon geschlossen. Aber nochmal zur Info: Mit den Mitteln, die wir mit GitHub Pages haben, ist ein Live-Tracking sicherlich nicht machbar. Wir haben keine Datenbank oder sowas, sondern es ist eine rein statische Umgebung, und alle Daten werden aus dem Repo heraus generiert, immer wenn eine Änderung stattgefunden hat. Zudem haben wir keine User-Accounts, sondern handeln mit für alle zugänglichen Daten. Die Infrastruktur ist für ein Live-Tracking also leider nicht ausgelegt.

Abgesehen davon: Gute Idee natürlich!
