### ISSUE TITLE
Eintrag Map

### ISSUE THREAD

**Issue by rotzek** [FriendsOfREDAXO/community#98]
Add or update your maps entry? → Please fill out the required fields below.
Your issue relates to another topic? → Please clear this text field and enter your text.

* name: Werbung, Hosting & IT - Thomas Rotzek
* latitude: 49.1042551
* longitude: 9.4892401
* bio: Seit über 10 Jahren realisieren wir Webseiten (knapp 300 inzwischen) aller Art ausschließlich mit redaxo!
* image: https://www.rotzek.de/theme/public/assets/frontend/images/logo.png
* links: https://www.rotzek.de

See `_directory/.data.example.yml` for detailed instructions!

**Comment by schuer** [comment]
Hey Tom, du bist schon drauf auf der Map!

<img width="463" alt="screenshot 2017-11-15 15 53 52" src="https://user-images.githubusercontent.com/1297466/32842379-3577e6f0-ca1d-11e7-9f47-116f32760cc1.png">

**Comment by staabm** [comment]
Ist schon drauf.
